### ISSUE TITLE
Importing a city doesn't work on Windows

### ISSUE THREAD

**Issue by Daniel1785** [a-b-street/abstreet#760]
![image](https://user-images.githubusercontent.com/91026326/133937066-c4e55604-5df2-4ffb-899c-be1a16457006.png)
i got to step 6, got this message as i tried to import my selected city

**Comment by dabreegster** [comment]
1) To check, are you using the latest 0.2.58 .zip?
2) Are you on Windows, Mac, or Linux?
3) Can you send the `output.txt` file that should appear in the main folder?

**Comment by Daniel1785** [comment]
1. I am, indeed.
2. Windows.
3. what's that?

**Comment by Daniel1785** [comment]
oh, nvm. found it. 
[2021-09-19T17:29:21Z WARN  map_gui::options] Couldn't restore settings, so using defaults. The system cannot find the file specified. (os error 2)
setup widgetry...
load textures...
[2021-09-19T17:29:21Z INFO  widgetry::backend_glow] img_size: 896x896px (802816 px), sprite_size: 64x64px, sprites: 14x14 (196 sprites)
load textures took 0.0461s
setup app...
create blank sim...
create blank sim took 0.0008s

- create blank sim took 0.0008s
[2021-09-19T17:29:21Z INFO  map_gui::render::map] static DrawMap consumes 0 MB on the GPU
setup app took 0.0028s
setup widgetry... plus 0.3086s
setup widgetry took 0.3576s

- setup widgetry took 0.3576s
  - load textures took 0.0461s
  - setup app took 0.0028s
  - ... plus 0.3086s
load ../data/system/us/phoenix/maps/gilbert.bin...

Reading ../data/system/us/phoenix/maps/gilbert.bin: 0/2 MB... 0.0001s
Read ../data/system/us/phoenix/maps/gilbert.bin (2)... 0.0834s

generate movements (629)... 0.0075s
create blank sim...

setup offstreet parking (609)... 0.0010s
create blank sim... plus 0.0092s
create blank sim took 0.0101s

- create blank sim took 0.0101s
  - setup offstreet parking (609)... 0.0010s
  - ... plus 0.0092s
draw_map...

make DrawRoads (790)... 0.0001s

make DrawLanes (3,598)... 0.0157s

make DrawIntersections (629)... 0.0002s
generate unzoomed roads and intersections...
generate unzoomed roads and intersections took 0.0047s

make DrawBuildings (609)... 0.0111s
upload all buildings...
upload all buildings took 0.0009s
make DrawParkingLot...
make DrawParkingLot took 0.0057s

make DrawAreas (49)... 0.0001s
upload all areas...
upload all areas took 0.0001s
create quadtree...
create quadtree took 0.0680s
[2021-09-19T17:29:21Z INFO  map_gui::render::map] static DrawMap consumes 0 MB on the GPU
draw_map... plus 0.0007s
draw_map took 0.1073s
screensaver traffic...
create blank sim...

setup offstreet parking (609)... 0.0008s
create blank sim... plus 0.0074s
create blank sim took 0.0082s

- create blank sim took 0.0082s
  - setup offstreet parking (609)... 0.0008s
  - ... plus 0.0074s
Generating scenario small_run...

SpawnOverTime each agent (100)... 0.0001s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

**Comment by dabreegster** [comment]
I think the output.txt file got cut off. Maybe https://pastebin.com/? Or just copy the last lines, that should be most relevant to the crash and failing to find the importer tool.

**Comment by Daniel1785** [comment]
SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

SpawnOverTime each agent (10)... 0.0000s

BorderSpawnOverTime (48)... 0.0003s
Generating scenario small_run... plus 0.0007s
Generating scenario small_run took 0.0015s
[2021-09-19T17:29:21Z WARN  sim::make::scenario] 0 of 2,020 people have nonsense schedules
Instantiating small_run...

trips for People (2,020)... 0.0013s

seed parked cars (271)... 0.0037s

spawn trips (2,020)... 0.0046s
Instantiating small_run... plus 0.0015s
Instantiating small_run took 0.0111s
screensaver traffic... plus 0.0138s
screensaver traffic took 0.0263s

- screensaver traffic took 0.0263s
  - Generating scenario small_run took 0.0015s
    - SpawnOverTime each agent (100)... 0.0001s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - SpawnOverTime each agent (10)... 0.0000s
    - BorderSpawnOverTime (48)... 0.0003s
    - ... plus 0.0007s
  - Instantiating small_run took 0.0111s
    - trips for People (2,020)... 0.0013s
    - seed parked cars (271)... 0.0037s
    - spawn trips (2,020)... 0.0046s
    - ... plus 0.0015s
  - ... plus 0.0138s
load ../data/system/us/phoenix/maps/gilbert.bin... plus 0.0409s
load ../data/system/us/phoenix/maps/gilbert.bin took 0.2391s

- load ../data/system/us/phoenix/maps/gilbert.bin took 0.2391s
  - Read ../data/system/us/phoenix/maps/gilbert.bin (2)... 0.0834s
  - generate movements (629)... 0.0075s
  - draw_map took 0.1073s
    - make DrawRoads (790)... 0.0001s
    - make DrawLanes (3,598)... 0.0157s
    - make DrawIntersections (629)... 0.0002s
    - generate unzoomed roads and intersections took 0.0047s
    - make DrawBuildings (609)... 0.0111s
    - upload all buildings took 0.0009s
    - make DrawParkingLot took 0.0057s
    - make DrawAreas (49)... 0.0001s
    - upload all areas took 0.0001s
    - create quadtree took 0.0680s
    - ... plus 0.0007s
  - ... plus 0.0409s
[2021-09-19T17:29:22Z INFO  sim::make::spawner] Bike trip from Building #75 to Building #66 will just walk; it's the same sidewalk!
[2021-09-19T17:29:22Z INFO  sim::make::spawner] Bike trip from Building #234 to Building #247 will just walk; it's the same sidewalk!
create blank sim...

setup offstreet parking (609)... 0.0010s
create blank sim... plus 0.0085s
create blank sim took 0.0095s

- create blank sim took 0.0095s
  - setup offstreet parking (609)... 0.0010s
  - ... plus 0.0085s
create blank sim...

setup offstreet parking (609)... 0.0009s
create blank sim... plus 0.0076s
create blank sim took 0.0085s

- create blank sim took 0.0085s
  - setup offstreet parking (609)... 0.0009s
  - ... plus 0.0076s
load scenario...
create people...

create people: making PersonSpec from endpoints (1,803)... 0.0055s
create people... plus 0.0030s
create people took 0.0085s
[2021-09-19T17:30:28Z INFO  sim::make::activity_model] TRIPS - total: 1,803, local: 224, commuting_in: 915, commuting_out: 120, passthru: 544, errored: 9, leftover_resident_capacity: 20, leftover_worker_capacity: 0
load scenario... plus 0.0002s
load scenario took 0.0086s

- load scenario took 0.0086s
  - create people took 0.0085s
    - create people: making PersonSpec from endpoints (1,803)... 0.0055s
    - ... plus 0.0030s
  - ... plus 0.0002s
instantiate scenario...
Instantiating random people going to and from work...

trips for People (1,794)... 0.0017s

seed parked cars (222)... 0.0030s

spawn trips (3,588)... 0.0088s
Instantiating random people going to and from work... plus 0.0018s
Instantiating random people going to and from work took 0.0153s
instantiate scenario... plus 0.0009s
instantiate scenario took 0.0162s

- instantiate scenario took 0.0162s
  - Instantiating random people going to and from work took 0.0153s
    - trips for People (1,794)... 0.0017s
    - seed parked cars (222)... 0.0030s
    - spawn trips (3,588)... 0.0088s
    - ... plus 0.0018s
  - ... plus 0.0009s
load ../data/system/us/phoenix/prebaked_results/gilbert/random people going to and from work.bin...
load ../data/system/us/phoenix/prebaked_results/gilbert/random people going to and from work.bin took 0.0004s

- load ../data/system/us/phoenix/prebaked_results/gilbert/random people going to and from work.bin took 0.0004s
[2021-09-19T17:30:28Z WARN  game::sandbox] No prebaked simulation results for "random people going to and from work" scenario on gilbert (in phoenix (us)) map. This means trip dashboards can't compare current times to any kind of baseline: The system cannot find the path specified. (os error 3)
rerendering map colors...

make DrawRoads (790)... 0.0001s

make DrawLanes (3,598)... 0.0138s

make DrawIntersections (629)... 0.0002s
generate unzoomed roads and intersections...
generate unzoomed roads and intersections took 0.0052s

make DrawBuildings (609)... 0.0106s
upload all buildings...
upload all buildings took 0.0010s
make DrawParkingLot...
make DrawParkingLot took 0.0058s

make DrawAreas (49)... 0.0000s
upload all areas...
upload all areas took 0.0001s
create quadtree...
create quadtree took 0.0696s
[2021-09-19T17:30:28Z INFO  map_gui::render::map] static DrawMap consumes 0 MB on the GPU
rerendering map colors... plus 0.0090s
rerendering map colors took 0.1154s

- rerendering map colors took 0.1154s
  - make DrawRoads (790)... 0.0001s
  - make DrawLanes (3,598)... 0.0138s
  - make DrawIntersections (629)... 0.0002s
  - generate unzoomed roads and intersections took 0.0052s
  - make DrawBuildings (609)... 0.0106s
  - upload all buildings took 0.0010s
  - make DrawParkingLot took 0.0058s
  - make DrawAreas (49)... 0.0000s
  - upload all areas took 0.0001s
  - create quadtree took 0.0696s
  - ... plus 0.0090s
load ../data/system/us/phoenix/city.bin...
load ../data/system/us/phoenix/city.bin took 0.0989s

- load ../data/system/us/phoenix/city.bin took 0.0989s
[2021-09-19T17:30:40Z INFO  map_gui::tools::command] RunCommand: ..\tools\one_step_import.exe boundary.geojson --use_overpass
Unknown winit key Snapshot

**Comment by Daniel1785** [comment]
sorry, didn't see it scrolled down

**Comment by Daniel1785** [comment]
@dabreegster just making sure you read this.

**Comment by dabreegster** [comment]
Yep, trying to figure out what's happening. I think it's a bug specific to Windows, and I don't have a Windows machine available to test. I fixed this problem in d41482febd2b1e4cedf5f420baba586ae6488fd6 I thought.

1) Are you running `play_abstreet.bat` to start things?
2) Can you verify that the main folder has a folder called `tools`, and that `one_step_import.exe` is inside there?

**Comment by Daniel1785** [comment]
1. yes, i am.
2. i can verify.

**Comment by Daniel1785** [comment]
2. i can't run the one_step_import_exe, if thats what you wanted me to do.

**Comment by Daniel1785** [comment]
okay, so now when i click on the button the game just crashes. it has gotten worse

**Comment by Daniel1785** [comment]
@dabreegster have you figured out the problem yet? just asking, no rush.

**Comment by Daniel1785** [comment]
okay, fixed! but 2 more questions:
1. do i have to do this everytime i open abstreet?
2. can i change the city name?

**Comment by dabreegster** [comment]
It's going to be hard to figure out why the relative path to the .exe isn't working in Windows, since it only seems to be happening there (not Mac or Linux) and I don't have a Windows machine handy. If anybody else reads this bug with a Windows machine and can help figure this out, it'd be appreciated.

You can also try the new release: https://github.com/a-b-street/abstreet/releases/tag/v0.2.59
I happened to move around the importing tools for #745. It's possible Windows is finding the first .exe, but then in the 0.2.58 version, it calls out to another tool, and that's what's failing. The new build would workaround that.

**Comment by Daniel1785** [comment]
so, i fixed it, i don't know how, but i opened it again and it worked, somewhere, somehow. no i just need to know if i can change the title.

**Comment by dabreegster** [comment]
Wait, the city import now works? Did you move files around? What changed? This software should be deterministic; things suddenly working or not working are not expected.

> do i have to do this everytime i open abstreet?

The imported city should still be there. When you reopen sandbox, it should actually start on the last map by default. If not, you'll see it in the list under the fake country code "zz":
![Screenshot from 2021-09-19 12-10-02](https://user-images.githubusercontent.com/1664407/133939871-aba3d61e-4063-4ac7-952f-54074bb042c3.png)

> can i change the city name?

Sorry, no. Importing a map this way is meant for initially trying things out. If you send the GeoJSON boundary you drew, I can import Tucson and it'll show up in the regular list.

**Comment by Daniel1785** [comment]
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -111.02027893066406,
              32.2507003471782
            ],
            [
              -111.02113723754883,
              32.19275598198777
            ],
            [
              -110.9153938293457,
              32.191157995229126
            ],
            [
              -110.90972900390625,
              32.195225542699454
            ],
            [
              -110.90972900390625,
              32.2072818473048
            ],
            [
              -110.8750534057617,
              32.20699135272648
            ],
            [
              -110.87522506713867,
              32.25055516937943
            ],
            [
              -111.02027893066406,
              32.2507003471782
            ]
          ]
        ]
      }
    }
  ]
}

**Comment by Daniel1785** [comment]
is that good to import it?

**Comment by dabreegster** [comment]
Sorry for the delay. Tucson is now imported, and you can import multiple places yourself without overwriting and with naming now:
![Screenshot from 2021-09-23 10-10-14](https://user-images.githubusercontent.com/1664407/134556495-cbfa7463-3976-41b3-b8c7-d5ebccb5a235.png)

I'm still not sure what's happening with the original problem here of not finding the .exe on Windows, but since it doesn't seem to be reproducible, I'll close for now. Thanks!
